#!/bin/bash

# Betiğin çalıştığı dizinin yolunu al
DIR="$(cd "$(dirname "$0")" && pwd)"

# Sanal ortam dizini
#VENV_DIR="$DIR/../share/crypto-dashboard/crypto-dashboard-venv"
VENV_DIR=".coindashboard-venv"

# Sanal ortam mevcut değilse oluştur
if [ ! -d "$VENV_DIR" ]; then
    echo "Sanal ortam oluşturuluyor..."
    python3 -m venv "$VENV_DIR"
    echo "Sanal ortam oluşturuldu."
fi

# Sanal ortamı etkinleştir
source "$VENV_DIR/bin/activate"

# Gerekli bağımlılıkları yükle
if [ -f "./requirements.txt" ]; then
    echo "Bağımlılıklar yükleniyor..."
    #pip install -r "$DIR/../share/crypto-dashboard/requirements.txt"
    pip install -r "./requirements.txt"
else
    echo "requirements.txt dosyası bulunamadı."
    exit 1
fi

# Uygulamayı çalıştır
if [ -f "./app.py" ]; then
    echo "Uygulama başlatılıyor..."
    #python3 "$DIR/../share/crypto-dashboard/app.py"
    python3 "./app.py"
else
    echo "app.py dosyası bulunamadı."
    exit 1
fi