#!/bin/bash

# Betiğin çalıştığı dizinin yolunu al
#DIR="$(cd "$(dirname "$0")" && pwd)"

# Sanal ortam dizini
#VENV_DIR="$DIR/../share/coindashboard/coindashboard-venv"
VENV_DIR=".coindashboard-venv"

# Sanal ortam mevcut değilse oluştur
if [ ! -d "$VENV_DIR" ]; then
    echo "Sanal ortam oluşturuluyor..."
    python3 -m venv "$VENV_DIR"
    echo "Sanal ortam oluşturuldu."
fi

# Sanal ortamı etkinleştir
source "$VENV_DIR/bin/activate"

# Gerekli bağımlılıkları yükle
echo "Bağımlılıklar yükleniyor..."
#pip install -r "$DIR/../share/coindashboard/requirements.txt"
pip install -r "./requirements.txt"

# Uygulamayı çalıştır
echo "Uygulama başlatılıyor..."
#python3 "$DIR/../share/coindashboard/app.py"
python3 "./app.py"