#!/bin/sh

# Paket bilgileri
version="3.0"
release="1"
package_name="coindashboard"

# RPM yapı dizinlerini temizleyin
echo "Önceki yapı dosyaları temizleniyor..."
rm -rf ~/rpmbuild/BUILD/${package_name}-${version}
rm -rf ~/rpmbuild/RPMS/noarch/${package_name}-${version}-${release}.noarch.rpm

# Kaynak ve RPM yapı dizinlerini oluşturun
mkdir -p ~/rpmbuild/SOURCES
mkdir -p ~/rpmbuild/BUILD/${package_name}-${version}/usr/bin
mkdir -p ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}
mkdir -p ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/applications

# Gerekli dosyaları kopyalayın
echo "Gerekli dosyalar kopyalanıyor..."
cp -r ./libs ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/libs
cp -r ./ui ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/ui
cp ./coindashboard ~/rpmbuild/BUILD/${package_name}-${version}/usr/bin/coindashboard
cp ./coindashboard_lock_app ~/rpmbuild/BUILD/${package_name}-${version}/usr/bin/coindashboard_lock_app
cp ./icon.png ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/icon.png
cp ./icon.ico ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/icon.ico
cp ./app.py ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/app.py
cp ./lock_app.py ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/lock_app.py
cp ./coindashboard.desktop ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/applications/coindashboard.desktop
cp ./coindashboard_lock_app.desktop ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/applications/coindashboard_lock_app.desktop
cp ./requirements.txt ~/rpmbuild/BUILD/${package_name}-${version}/usr/share/${package_name}/requirements.txt

# SPEC dosyasını oluşturun
echo "SPEC dosyası oluşturuluyor..."
cat > ~/rpmbuild/SPECS/${package_name}.spec <<EOL
Name:           ${package_name}
Version:        ${version}
Release:        ${release}%{?dist}
Summary:        Crypto Dashboard Application

License:        GPL
URL:            http://your-url.com/
Source0:        %{name}-%{version}.tar.gz
BuildArch:      noarch

BuildRequires:  python3, python3-virtualenv
Requires:       python3

%description
A comprehensive dashboard for monitoring cryptocurrency markets.
Provides real-time insights and analysis on crypto trends, helping users to make informed trading decisions.

%prep
%setup -q

%build

%install
# Kurulum dizinini oluştur
mkdir -p %{buildroot}/usr/bin
mkdir -p %{buildroot}/usr/share/%{name}
mkdir -p %{buildroot}/usr/share/applications

# Dosyaları kopyalayın
cp -a * %{buildroot}/usr/share/%{name}
cp -a usr/bin/* %{buildroot}/usr/bin/
cp -a usr/share/applications/* %{buildroot}/usr/share/applications/

%post
# Sanal ortam oluştur
VENV_DIR="/usr/share/%{name}/%{name}-venv"
if [ ! -d "\$VENV_DIR" ]; then
    echo "Sanal ortam oluşturuluyor..."
    python3 -m venv "\$VENV_DIR"
    source "\$VENV_DIR/bin/activate"
    pip install -r "/usr/share/%{name}/requirements.txt"
    echo "Bağımlılıklar yüklendi."
fi

%preun
# Sanal ortamı kaldır
VENV_DIR="/usr/share/%{name}/%{name}-venv"
if [ -d "\$VENV_DIR" ]; then
    echo "Sanal ortam kaldırılıyor..."
    rm -rf "\$VENV_DIR"
fi

%files
/usr/bin/coindashboard
/usr/bin/coindashboard_lock_app
/usr/share/%{name}
/usr/share/applications/coindashboard.desktop
/usr/share/applications/coindashboard_lock_app.desktop

%changelog
* Sun Aug 04 2024 Fatih Yolcu <kilicsizoglu@gmail.com> - ${version}-${release}
- Initial release
EOL

# Kaynak dosyalarını arşivleyin
echo "Kaynak dosyaları arşivleniyor..."
tar -czf ~/rpmbuild/SOURCES/${package_name}-${version}.tar.gz -C ~/rpmbuild/BUILD/ ${package_name}-${version}

# RPM paketini oluşturun
echo "RPM paketi oluşturuluyor..."
rpmbuild -ba ~/rpmbuild/SPECS/${package_name}.spec

# Oluşturulan RPM paketini kontrol edin
echo "RPM paketi oluşturuldu: ~/rpmbuild/RPMS/noarch/${package_name}-${version}-${release}.noarch.rpm"
